apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeserve
spec:
  replicas: 4
  minReadySeconds: 45 # wait for 45 sec before pod is ready going to next
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  
      maxSurge: 2        
  selector:
    matchLabels:
      app: kubeserve
  template:
    metadata:
      name: kubeserve
      labels:
        app: kubeserve
    spec:
      containers:
      - image: leaddevops/kubeserve:v1
        name: app

# ---
# kind: Service
# apiVersion: v1
# metadata:
#    name: kubeserve-svc
# spec:
#   type: NodePort
#   selector: 
#     app: kubeserve
#   ports:
#     - port: 80
#       targetPort: 80
